config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'users#home'
  get '/users/show/:id' => 'users#show', :as => :show_user
  get '/users/show_followers/:id' => 'users#show_followers', :as => :show_followers
  get '/users/show_followeds/:id' => 'users#show_followeds', :as => :show_followeds
  get '/users/show_unfollowed_users/:id' => 'users#show_unfollowed_users', :as => :show_unfollowed_users
  get '/users/show_tweets/:id'    => 'users#show_tweets',    :as => :show_tweets
  get '/tweets/new' => 'tweets#new'
  post '/tweets/create' => 'tweets#create'
  post '/users/follow_user/:id' => 'users#follow_user', :as => :follow_user
  post '/users/unfollow_user/:id' => 'users#unfollow_user', :as => :unfollow_user

end

app/models/following.rb
class Following < ActiveRecord::Base

  belongs_to :user
  belongs_to :followed, :class_name => 'User', :foreign_key => :follower_id
  belongs_to :follower, :class_name => 'User', :foreign_key => :followed_id

  validates :follower_id, :presence => true
  validates :followed_id, :presence => true

  validates_uniqueness_of :follower_id, :scope => [:followed_id], :message => "already following that user"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  MAX_TWEET_LENGTH = 144

  validates :user_id, :presence => true
  validates :content, :presence => true
  validates_length_of :content, :maximum => MAX_TWEET_LENGTH

#TODO: REFACTOR/FIX -- surely AR has a way to do this elegantly but I couldn't find it and used this hack
  before_update :disallow_updates

  def disallow_updates
    raise "tweets can not be updated"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :followings
  has_many :followeds, :through => :followings, :foreign_key => :followed_id, :class_name => 'User'
  has_many :followers, :through => :followings, :foreign_key => :follower_id, :class_name => 'User'
  has_many :tweets

  validates :username,
            :presence => true,
            :uniqueness => {
                :case_sensitive => false
            }
  #NOTE: gem validates_email_format_of also checks for presence, and for uniqueness (case insensitive)
  validates_email_format_of :email, :message => 'does not look like a valid email address'

  after_create :follow_self

  def follow(other_user)
    following = Following.create(:follower_id => self.id, :followed_id => other_user.id)
    if following.valid?
      return true
    else
      raise following.errors.messages.values.join('\n')
    end
  end

  def unfollow(other_user)
    raise "can not unfollow yourself" if (self.id == other_user.id)
    following = Following.where(["follower_id = ? and followed_id = ?", self.id, other_user.id]).first
    #NOTE: in theory ActiveRecord::Relation might be returning > 1 value if that was somehow created in the database but we are trusting that is not the case cuz of tweet validations
    raise "not following that user" if following.nil?
    Following.delete(following.id)
    true
  end

#TODO: add rspec for last-minute added query methods num_followers, num_followees and num_tweets
  def num_followers
    follower_ids = Following.where(:followed_id => self.id).pluck(:follower_id)
    follower_ids.size - 1  #don't count yourself
  end

  def num_followeds
    followed_ids = Following.where(:follower_id => self.id).pluck(:followed_id)
    followed_ids.size - 1   #don't count yourself
  end

  def num_tweets
    tweet_ids = Tweet.where(:user_id => self.id).pluck(:id)
    tweet_ids.size
  end

  #TODO! REFACTOR: followers and followeds are N+1 query situation that needs eager loading fixes;
  # (finding optimal way via with AR in rails 4 was slow and ambigiuous, so temp-only doing N+1 way to make it work (n is still small for now, at least, anyway))
  def followers
    follower_ids = Following.where(:followed_id => self.id).order(:follower_id).pluck(:follower_id)
    ret_val = []
    follower_ids.each do |follower_id|
      ret_val << User.find(follower_id)
    end
    ret_val
  end

  def followeds
    followed_ids = Following.where(:follower_id => self.id).order(:followed_id).pluck(:followed_id)
    ret_val = []
    followed_ids.each do |followed_id|
      ret_val << User.find(followed_id)
    end
    ret_val
  end

  def unfollowed_users
    User.all - followeds
  end

  def create_tweet(content)
    tweet = Tweet.create(:user_id => self.id, :content => content)
    if tweet.valid?
      return tweet
    else
      raise tweet.errors.messages.values.join('\n')
    end
  end

  def get_all_tweets
    Tweet.where(:user_id => self.id).order(:user_id).to_a
  end

private
  def follow_self
    follow(self)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

#TODO: move to helper method
  #set user to current_user if going to their own page, or to an invalid id
  # (we want to not reward tinkering behavior with user ids that don't exist.. just send them to their own page)
  def get_user_or_current_user(id)
    id = params[:id]
    if id == current_user.id
      return current_user
    end
    user = User.find_by_id(id)
    if user.nil?
      return current_user
    else
      return user
    end

  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  # def show_tweets
  #   @user = get_user_or_current_user(params[:id])
  # end

  def new
    @tweet = Tweet.new
    @hide_header = true
  end

  def create
    @user = current_user
    @content = params[:tweet][:content]
    @tweet = Tweet.new
    @tweet.user_id = @user.id
    @tweet.content = @content
    if @tweet.valid?
      @tweet.save!
      redirect_to show_tweets_path(@user.id)
    else
      logger.warn '*************** ERRORS ************************'
      logger.warn @tweet.errors.inspect
      flash.now[:danger] = "ERROR: #{@tweet.errors}"
      redirect_to tweets_new_path()    end
  end

  # def tweet_form
  #   render
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def home
    redirect_to show_user_path(current_user.id)
  end

#TODO: refactor check for current user and redirects when not correct
# (can't seem to change /id in url due to circular redirect, might want to just show indication user doesn't exist, or add a route without an id?)
  def show
    @user = get_user_or_current_user(params[:id])
    @is_current_user = (@user.id == current_user.id)
  end

  def show_followers
    @user = get_user_or_current_user(params[:id])
    @is_current_user = (@user.id == current_user.id)
    @followers = @user.followers - [@user]
  end

  def show_followeds
    @user = get_user_or_current_user(params[:id])
    @is_current_user = (@user.id == current_user.id)
    @followeds = @user.followeds - [@user]
  end

#TODO: added ordering near end of dev, add test for this
  def show_tweets
    @user = get_user_or_current_user(params[:id])
    @tweets = Tweet.where(:user_id => @user.id).order(created_at: :desc)
  end

  def show_unfollowed_users
    @user = get_user_or_current_user(params[:id])
    @unfollowed_users = @user.unfollowed_users - [@user]
  end

  def follow_user
    @user_to_follow = User.find_by_id(params[:id])
    begin
      current_user.follow(@user_to_follow)
    rescue RuntimeError => re
      logger.error "error following from user #{current_user.id} to #{params[:id]}"
    end
    redirect_to show_unfollowed_users_path(current_user.id)
  end

  def unfollow_user
    @user_to_unfollow = User.find_by_id(params[:id])
    logger.warn "current user #{current_user.id} trying to unfollow other user #{@user_to_unfollow.id}"
    begin
      current_user.unfollow(@user_to_unfollow)
    rescue RuntimeError => re
      logger.error "error unfollowing from user #{current_user.id} to #{params[:id]}"
    end
    redirect_to show_followeds_path(current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheets" href="styles.css">
  <title>TwitterDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header_links">
<% unless @hide_header %>
    <% if user_signed_in? %>
        <span class="home_link"><%= link_to('Home', show_user_url(current_user.id), :method => :get) %></span>
        <span class="create_tweet"> <%= link_to('Create a tweet', tweets_new_path, :method => :get) %> </span>
        <span class="unfollowed_users_link"><%= link_to('Who to follow', show_unfollowed_users_url(@user.id), :method => :get) %></span>
        <span class="logout_link"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></span>

    <% end %>
<% end %>
</div>
    <%= yield %>

</body>
</html>

app/views/tweets/new.html.erb
<div class="create_tweet"><%= form_for @tweet, url: {action: "create"} do |f| %>
    <%= f.text_field :content %>
    <%= f.submit "Just Tweet It" %>
<% end %></div>

app/views/tweets/show_tweets.html.erb
<% @user.get_all_tweets.each do |tweet| %>
<p>
<tr><td>Time tweeted</td><td>Tweet Content</td></tr>
  <br>
<tr><td><%= tweet.created_at %></td><td><%= tweet.content %></td></tr>
</p>
<br>
<% end %>

app/views/users/show.html.erb
<br>
<p>
</p>
<br>
<div class="home_view_username">
<span>
  <% if @is_current_user %>
    Welcome back, <%= @user.username %>!
  <% else %>
    Home page of <%= @user.username %>
  <% end %>
</span>
  </div>
<br><br><br><br>
  <table class="user_show_table">
    <tr>
      <td class="user_home_show_td"> <%= link_to('Following', show_followeds_url(@user.id), :method => :get) %> </td>
      <td class="user_home_show_td"> <%= link_to('Followers', show_followers_url(@user.id), :method => :get) %> </td>
      <td class="user_home_show_td"> <%= link_to('Tweets', show_tweets_url(@user.id), :method => :get) %> </td>
    </tr>
    <tr>
      <td class="user_home_show_td"> <%= @user.num_followeds %> </td>
      <td class="user_home_show_td"> <%= @user.num_followers %> </td>
      <td class="user_home_show_td"> <%= @user.num_tweets %> </td>
    </tr>
  </table>

app/views/users/show_followeds.html.erb
<br><br>
<div class="follow_view_username">
  <% if @is_current_user %>
      <%= @user.username %>, users you are following . . .
  <% else %>
    <%= @user.username %> is following . . .
  <% end %>
</div>
<br><br><br><br><br>

<% @followeds.each do |followed| %>
    <table class="user_show_table">
      <tr>
        <td class="user_follow_show_td"> <%= link_to(followed.username, show_user_url(followed.id), :method => :get) %> </td>
        <td class="user_follow_show_td"> <%= link_to('Following', show_followers_url(followed.id), :method => :get) %> </td>
        <td class="user_follow_show_td"> <%= link_to('Followed by', show_followeds_url(followed.id), :method => :get) %> </td>
        <td class="user_follow_show_td"> <%= link_to('Tweets', show_tweets_url(followed.id), :method => :get) %> </td>
      </tr>
      <tr>
        <% if @is_current_user %>
            <td class="user_follow_show_td"> <%= link_to('Unfollow', unfollow_user_url(followed.id), :method => :post) %> </td>
        <% end %>
        <td class="user_follow_show_td"> <%= followed.num_followers %> </td>
        <td class="user_follow_show_td"> <%= followed.num_followeds %> </td>
        <td class="user_follow_show_td"> <%= followed.num_tweets %> </td>
      </tr>
    </table>
    <br>
<% end %>

app/views/users/show_followers.html.erb
<br><br>
<div class="follow_view_username">
  <%= @user.username %>'s followers:</div>
<br><br><br><br><br>

<% @followers.each do |follower| %>
    <table class="user_show_table">
      <tr>
        <td class="user_follow_show_td"> <%= link_to(follower.username, show_user_url(follower.id), :method => :get) %> </td>
        <td class="user_follow_show_td"> Following <%= link_to(follower.num_followeds, show_followeds_url(follower.id), :method => :get) %></td>
        <td class="user_follow_show_td"> Followed by <%= link_to(follower.num_followers, show_followers_url(follower.id), :method => :get) %></td>
        <td class="user_follow_show_td"> Tweets <%= link_to(follower.num_tweets,show_tweets_url(follower.id), :method => :get) %>  </td>
      </tr>
    </table>
<br>
<% end %>

app/views/users/show_tweets.html.erb
<div class="tweeter_username">Tweets by <%= @user.username %> . . .</div>
<br><br><br><br><br><br>
<% @tweets.each do |tweet| %>
<div class="tweet_row">
<span class="tweet_date"><%= tweet.created_at.strftime("%m %b %Y,%l:%M%P") %> </span>
<span class="tweet"> -- <%= tweet.content %> </span>
</div>
    <br>
<% end %>

app/views/users/show_unfollowed_users.html.erb
<br><br>
<div class="follow_view_username">Users you might follow . . .</div>
<br><br><br><br><br>

<% @unfollowed_users.each do |unfollowed_user| %>
    <table class="user_show_table">
      <tr>
        <td class="user_follow_show_td"> <%= link_to(unfollowed_user.username, show_user_url(unfollowed_user.id), :method => :get) %> </td>
        <td class="user_follow_show_td"> <%= link_to('Following', show_followers_url(unfollowed_user.id), :method => :get) %> </td>
        <td class="user_follow_show_td"> <%= link_to('Followed by', show_followeds_url(unfollowed_user.id), :method => :get) %> </td>
        <td class="user_follow_show_td"> <%= link_to('Tweets', show_tweets_url(unfollowed_user.id), :method => :get) %> </td>
      </tr>
      <tr>
        <td class="user_follow_show_td"> <%= link_to('Follow', follow_user_url(unfollowed_user.id), :method => :post) %> </td>
        <td class="user_follow_show_td"> <%= unfollowed_user.num_followers %> </td>
        <td class="user_follow_show_td"> <%= unfollowed_user.num_followeds %> </td>
        <td class="user_follow_show_td"> <%= unfollowed_user.num_tweets %> </td>
      </tr>
    </table>
    <br>
<% end %>